import type { Metadata } from "next";
import LegalLayout from "@/components/LegalLayout";

export const metadata: Metadata = { title: "Privacy Notice — CryptoTrade" };

const sections = [
  {
    id: "overview",
    heading: "1. Overview",
    body: [
      "This privacy notice explains what personal data we collect, how we use it, and the choices you have regarding your information when you use CryptoTrade.",
    ],
  },
  {
    id: "data-we-collect",
    heading: "2. Data we collect",
    body: [
      "We collect information you provide directly, such as your name, email address and identity verification documents, as well as information generated by your use of the platform, such as transaction history and device data.",
    ],
  },
  {
    id: "how-we-use-it",
    heading: "3. How we use your data",
    body: [
      "We use personal data to provide and improve our services, comply with legal and regulatory obligations, detect fraud, and communicate important account information.",
    ],
  },
  {
    id: "sharing",
    heading: "4. Sharing your data",
    body: [
      "We share data with service providers who help us operate the platform, and with regulators or law enforcement where required by law. We do not sell your personal data.",
    ],
  },
  {
    id: "your-rights",
    heading: "5. Your rights",
    body: [
      "Depending on your jurisdiction, you may have the right to access, correct, delete or export your personal data. You can exercise these rights by contacting our support team.",
    ],
  },
  {
    id: "retention",
    heading: "6. Data retention",
    body: [
      "We retain personal data for as long as necessary to provide our services and to comply with legal, tax and regulatory obligations.",
    ],
  },
  {
    id: "contact",
    heading: "7. Contact us",
    body: [
      "If you have questions about this privacy notice, please reach out through our contact page.",
    ],
  },
];

export default function PrivacyPage() {
  return <LegalLayout title="Privacy notice" updated="August 1, 2026" sections={sections} />;
}
